FROM ubuntu:trusty
MAINTAINER Ross McDonald <mcdonaldrossc+docker@gmail.com>

RUN apt-get update && \
    apt-get install -y \
    build-essential \
    gcc \
    gcc-multilib \
    bison \
    binutils \
    git \
    mercurial \
    curl \
    ruby-dev \
    rpm \
    zip \
    python-boto \
    python-apt \
    python-dev \
    python-pip

RUN gem install fpm
RUN pip install ansible

# Install go
ENV GO_VERSION 1.5.3
ENV GO_ARCH amd64
RUN curl -sLO https://storage.googleapis.com/golang/go${GO_VERSION}.linux-${GO_ARCH}.tar.gz && \
   tar -C /usr/local/ -xf /go${GO_VERSION}.linux-${GO_ARCH}.tar.gz && \
   rm /go${GO_VERSION}.linux-${GO_ARCH}.tar.gz
ENV PATH /usr/local/go/bin:$PATH
ENV GOPATH /usr/local/go

ENV PROJECT_DIR /ansible
RUN mkdir $PROJECT_DIR

WORKDIR $PROJECT_DIR
VOLUME $PROJECT_DIR
ENTRYPOINT [ "ansible-playbook", "-c", "local", "-e", "is_docker=true" ]
